site_name: CECLE Machine Docs
site_url: https://doc.cecle.net/ 
theme:
  name: material

nav:
  - Official Website: https://cecle.net
  - Home: index.md
  - Packing Machinery:
      - Cellophane Wrapping Machine:
          - Overview: packing-machine/cellophane-wrapping-machine/cellophane-wrapping-machine.md
          - ACW-88 Automatic: packing-machine/cellophane-wrapping-machine/acw-88.md
          - ACW-88D Dot Heat: packing-machine/cellophane-wrapping-machine/acw-88d.md
          - ACW-88F Film Rewind : packing-machine/cellophane-wrapping-machine/acw-88f.md
          - ACW-88T Tear Tape: packing-machine/cellophane-wrapping-machine/acw-88t.md
          - CW-88 Small: packing-machine/cellophane-wrapping-machine/cw-88.md
          - CW-88A Electric: packing-machine/cellophane-wrapping-machine/cw-88a.md
          - CW-115 Manual: packing-machine/cellophane-wrapping-machine/cw-115.md
  - Food Machinery:
      - Samosa Making Series:
          - Overview: food-machine/samosa-making-machine/samosa-making-machine-index.md
          - Automatic: food-machine/samosa-making-machine/automatic-series.md
          - Semi: food-machine/samosa-making-machine/semi-automatic-series.md