site_name: CECLE Machine Docs
site_url: https://doc.cecle.net/ 
theme:
  name: material

nav:
  - 首页: index.md
  - 包装机械 (Packing Machinery):
      - 透明膜三维包装机:
          - 系列产品概览: packing-machine/cellophane-wrapping-machine/cellophane-wrapping-machine.md
          - ACW-88 基础款全自动: packing-machine/cellophane-wrapping-machine/acw-88.md
          - ACW-88D 带点烫功能型: packing-machine/cellophane-wrapping-machine/acw-88d.md
          - ACW-88F 收废膜版: packing-machine/cellophane-wrapping-machine/acw-88f.md
          - ACW-88T 带易撕线款: packing-machine/cellophane-wrapping-machine/acw-88t.md
          - CW-88 手动紧凑型: packing-machine/cellophane-wrapping-machine/cw-88.md
          - CW-88A 电动紧凑型: packing-machine/cellophane-wrapping-machine/cw-88a.md
          - CW-115 纯手动烫板: packing-machine/cellophane-wrapping-machine/cw-115.md
  - 食品机械(Food Machinery):
      - 咖喱角成型机系列:
          - 系列产品概览: food-machine/samosa-making-machine/samosa-making-machine-index.md
          - 自动系列: food-machine/samosa-making-machine/automatic-series.md
          - 半自动系列: food-machine/samosa-making-machine/semi-automatic-series.md