site_name: CECLE Machine Docs
site_url: https://doc.cecle.net/ 
theme:
  name: material
  language: en
  features:
    - content.code.copy
    - i18n.language.switch # 🌟 检查这一行是否已经加上，前面要有两个空格对齐
plugins:
  - search
  - i18n:
      default_language: en
      languages:
        - locale: en
          name: English
          default: true
        - locale: zh
          name: 简体中文
        - locale: es
          name: Español
        - locale: fr
          name: Français
        - locale: pt
          name: Português (Brasil)
        - locale: ar
          name: العربية
        - locale: id
          name: Indonesia
        - locale: vi
          name: Tiếng Việt
        - locale: th
          name: ภาษาไทย
        - locale: pl
          name: Polski
        - locale: de
          name: Deutsch
        - locale: ru
          name: Русский
        - locale: tr
          name: Türkçe
        - locale: it
          name: Italiano
extra_javascript:
  - js/redirect.js
nav:
  - Official Website: https://cecle.net
  - Home: index.md
  - Packing Machinery:
      - Cellophane Wrapping Machine:
          - Overview: packing-machine/cellophane-wrapping-machine/cellophane-wrapping-machine-index.md
          - ACW-88 Automatic: packing-machine/cellophane-wrapping-machine/acw-88.md
          - ACW-88D Dot Heat: packing-machine/cellophane-wrapping-machine/acw-88d.md
          - ACW-88F Film Rewind : packing-machine/cellophane-wrapping-machine/acw-88f.md
          - ACW-88T Tear Tape: packing-machine/cellophane-wrapping-machine/acw-88t.md
          - CW-88 Small: packing-machine/cellophane-wrapping-machine/cw-88.md
          - CW-88A Electric: packing-machine/cellophane-wrapping-machine/cw-88a.md
          - CW-115 Manual: packing-machine/cellophane-wrapping-machine/cw-115.md
      - Blister Packing Machine:
          - Overview: packing-machine/Blister-Packing-Machine/blister-packing-machine-index.md
          - MTBP-180 Benchtop Entry-level: packing-machine/Blister-Packing-Machine/mtbp-180.md
          - TBP-180 Benchtop Pneumatic: packing-machine/Blister-Packing-Machine/tbp-180.md
          - ETBP-180 Benchtop Electric: packing-machine/Blister-Packing-Machine/etbp-180.md
          - BP-180 Vertical Basic: packing-machine/Blister-Packing-Machine/bp-180.md
          - CP-180 Vertical Standard: packing-machine/Blister-Packing-Machine/cp-180.md
          - DP-180 Vertical Upgraded: packing-machine/Blister-Packing-Machine/dp-180.md
          - DPP-80 Fully Automatic Small: packing-machine/Blister-Packing-Machine/dpp-80.md
          - DPP-150 Fully Automatic Medium: packing-machine/Blister-Packing-Machine/dpp-150.md
          - DPP-260 Fully Automatic Large: packing-machine/Blister-Packing-Machine/dpp-260.md
      - Blister Sealing Machine:
          - Overview: packing-machine/blister-sealing-machine/blister-sealing-machine-index.md
          - BS-2030 Mold Heating: packing-machine/blister-sealing-machine/bs-2030.md
          - BS-2037 Mold Heating: packing-machine/blister-sealing-machine/bs-2037.md
          - BS-3180 Mold Heating: packing-machine/blister-sealing-machine/bs-3180.md
          - BS-5030 Mold Heating: packing-machine/blister-sealing-machine/bs-5030.md
          - BS-5070 Mold Heating: packing-machine/blister-sealing-machine/bs-5070.md
          - UBS-5030 Heating Plate Type: packing-machine/blister-sealing-machine/ubs-5030.md
          - HFQ-01 High Frequency: packing-machine/blister-sealing-machine/hfq-01.md
          - HFQ-02 / HFQ-03 High Frequency: packing-machine/blister-sealing-machine/hfq-02-hfq-03.md
          - HFQ-04 / HFQ-05 High Frequency: packing-machine/blister-sealing-machine/hfq-04-hfq-05.md
      - Blister Cutting Machine:
          - ETBPC-180 Electric Benchtop: packing-machine/blister-cutting-machine/etbpc-180.md
      - Honey Straw Filling Machine:
          - Overview: packing-machine/filling-machine/honey-straw-filling-machine/honey-straw-filling-machine-index.md
      - Vacuum Skin Packaging Machine:
          - Overview: packing-machine/vacuum-skin-packaging-machine/vacuum-skin-packing-machine-index.md
          - RVSP-4634 Rotary Type: packing-machine/vacuum-skin-packaging-machine/rvsp-4634.md
          - VSP-4634 Drawer Type: packing-machine/vacuum-skin-packaging-machine/vsp-4634.md
          - Desktop Manual Type: packing-machine/vacuum-skin-packaging-machine/desktop.md
      - Modified Atmosphere Packaging Machine:
          - Overview: packing-machine/modified-atmosphere-packaging-machine/modified-atmosphere-packaging-machine-index.md
          - AMAP-5827 Continuous Type: packing-machine/modified-atmosphere-packaging-machine/amap-5827-modified-atmosphere-packaging-machine.md
          - MAP-4634 Drawer Type: packing-machine/modified-atmosphere-packaging-machine/map-4634-drawer-type.md
          - RMAP-4634 Rotary Type: packing-machine/modified-atmosphere-packaging-machine/rmap-4634-modified-atmosphere-packaging-machine.md
      - Conveyor & Feeder Series:
          - Overview: packing-machine/screw-conveyor/conveyor&feeder-index.md
          - Powder Screw Conveyor: packing-machine/screw-conveyor/powder-screw-conveyor.md
          - Flexible Screw Conveyor: packing-machine/screw-conveyor/flexible-screw-conveyor.md
          - Horizontal Screw Feeder: packing-machine/screw-conveyor/horizontal-screw-feeder.md
          - Loss-in-weight Screw Feeder SC40: packing-machine/screw-conveyor/loss-in-weight-screw-feeder-SC40.md
          - Liquid Feeding Machine: packing-machine/screw-conveyor/liquid-feeding-machine.md
          - Climbing Belt Conveyor: packing-machine/screw-conveyor/climbing-belt-conveyor.md
          - Bucket Elevator: packing-machine/screw-conveyor/bucket-elevator.md
          - Z-type Bucket Elevator: packing-machine/screw-conveyor/z-type-bucket-elevator.md
      - Stand-up Pouch Packing Machine:
          - Overview: packing-machine/stand-up-pouch-packing-machine/stand-up-pouch-packing-machine-index.md
          - Granule Pouch Packing: packing-machine/stand-up-pouch-packing-machine/granule-stand-up-pouch-packing-machine.md
          - Liquid Pouch Packing: packing-machine/stand-up-pouch-packing-machine/liquid-stand-up-pouch-packing-machine.md
          - Powder Pouch Packing: packing-machine/stand-up-pouch-packing-machine/powder-stand-up-pouch-packing-machine.md
      - Printing Machine: 
          - Screen Printing Machine:
              - Overview: packing-machine/printing-machine/screen-printing-machine/screen-printing-machine-index.md
              - Automatic Series: packing-machine/printing-machine/screen-printing-machine/automatic-series.md
              - Manual Series: packing-machine/printing-machine/screen-printing-machine/manual-series.md
              - Cylindrical Series: packing-machine/printing-machine/screen-printing-machine/cylindrical-series.md
              - Flat Big Series: packing-machine/printing-machine/screen-printing-machine/flat-big-series.md
              - Flat TD-1518: packing-machine/printing-machine/screen-printing-machine/flat-td-1518.md
              - Flat TD-1525: packing-machine/printing-machine/screen-printing-machine/flat-td-1525.md
              - Flat TD-2030SF: packing-machine/printing-machine/screen-printing-machine/flat-td-2030sf.md
              - Flat TD-2533: packing-machine/printing-machine/screen-printing-machine/flat-td-2533.md
              - UV Curing Machine: packing-machine/printing-machine/screen-printing-machine/uv-curing-machine.md
  - Food Machinery:
      - Samosa Making Series:
          - Overview: food-machine/samosa-making-machine/samosa-making-machine-index.md
          - Automatic: food-machine/samosa-making-machine/automatic-series.md
          - Semi: food-machine/samosa-making-machine/semi-automatic-series.md
          - Punjabi Samosa: food-machine/samosa-making-machine/punjabi-samosa.md